# Site settings
title: Nachhilfe Fischer
title2: Nachhilfe Mathe und Elektrotechnik
email: marius-fischer30@gmx.de
url: https://jeromelachaud.com/freelancer-theme
description: "Nachhilfe in Mathe & Elektrotechnik für Schüler und Berufsschüler – verständliche Erklärungen, praxisnahe Beispiele und gezielte Prüfungsvorbereitung. Unterricht persönlich oder online."
keywords: "Mathe Nachhilfe, Elektrotechnik Nachhilfe, Nachhilfe Paderborn, Nachhilfe Lippstadt, Nachhilfe Owl, Abitur Mathe, Berufsschule Elektrotechnik, Online Nachhilfe, Prüfungsvorbereitung Mathe, Prüfungsvorbereitung Elektrotechnik, technische Nachhilfe"
skills: "Nachhilfe bis Abitur, Berufsschule & weiteres - verständliche Erklärungen komplexer Sachverhalte - praxisnahe Beispiele - individuelle Förderung"
meta_author: Fischer Marius

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Ort
  social: Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: kleinanzeigen
    url: https://www.kleinanzeigen.de/s-anzeige/mathe-elektrotechnik-nachhilfe-bis-abitur-berufsschule-/3496955478-268-2158
  - title: google 
    url: https://maps.app.goo.gl/bLDHF7RZEiAJiZJM7
 # - title: twitter
 #   url: http://twitter.com/jekyllrb
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #  url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
 # - title: github
 #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Widukindstraße 21
  - line: 33098 Paderborn

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
